YJDH-645 | KS-Backend: Stream Excel export
City-of-Helsinki/yjdh pull request #1345
Opened 2022-08-18 14:39 UTC by karisal-anders

## Description :sparkles:

### KS-Backend: Add xlsx-streaming Python package 

Refs YJDH-645 (The package to be used for streaming .xlsx files)
 
### KS-Backend: Make Excel export really stream XLSX files 

Refs YJDH-642 (The bug this fix is related to)
Refs YJDH-645 (A fix for YJDH-642)

### KS-Backend: Add type hints, EXCEL_DOWNLOAD_BATCH_SIZE setting

 - Add type hints to some of the functions in excel_exporter.py.
 - Configure Excel download batch size in Excel exporting with setting
   EXCEL_DOWNLOAD_BATCH_SIZE and default value of 50.
 - Add comment to generate_xlsx_template function in excel_exporter.py.

Refs YJDH-645

### KS-Backend: Make Excel download's row order predictable

EmployerApplicationExcelDownloadView:
 - Use triplet (submitted_at, created_at, pk) as the sorting key for the
   Excel download's queryset. Use the same triplet in the queryset's
   order_by clause and the RowNumber window function annotation's
   order_by clause to make the row numbers work correctly. Using
   created_at and primary key as the secondary and tertiary ordering
   parameters to force a predictable although slightly arbitrary
   ordering for queryset rows with identical submitted_at values.

Tests:
 - Add test test_excel_view_download_no_annual_applications to test that
   drafts are not included in the annual Excel downloads and that if
   there are only drafts then nothing is returned.
 - Extend test_excel_view_download_content to test a case where
   submitted_at timestamp is the same and thus the created_at secondary
   sorting key for the Excel download's output should be used.

Factories:
 - Add DuplicateAllowingUserFactory into shared code
   - Creates or gets a Django user with a possibly duplicated username
 - Use DuplicateAllowingUserFactory for EmployerApplicationFactory.user
   - Now creating hundreds of EmployerApplications using
     EmployerApplicationFactory doesn't fail because of duplicate
     usernames (This happened often during testing when creating hundred
     of EmployerApplications)

Refs YJDH-645

## Issues :bug:

YJDH-642 (The bug this fix is related to)
YJDH-645 (A fix for YJDH-642)

## Testing :alembic:

For developers locally:
 - NOTE: These testing instructions are for an empty yjdh_pgdata Docker volume. If you have a working volume already please remove it first or you're on your own.
 - Build the Kesäseteli's backend and the employer frontend:
   - `yarn employer:build`
 - Generate data to test Excel export with:
   - `docker exec -it kesaseteli-backend bash`
   - `python manage.py shell_plus`
   - `from applications.enums import EmployerApplicationStatus`
   - `from applications.models import EmployerApplication, EmployerSummerVoucher`
   - `from common.tests.factories import EmployerApplicationFactory, EmployerSummerVoucherFactory`
   - `for _ in range(51): EmployerSummerVoucherFactory(application=EmployerApplicationFactory(status=EmployerApplicationStatus.DRAFT))`
   - `for _ in range(52): EmployerSummerVoucherFactory(application=EmployerApplicationFactory(status=EmployerApplicationStatus.SUBMITTED))`
   - `for _ in range(53): EmployerApplicationFactory(status=EmployerApplicationStatus.DRAFT)`
   - NOTE: If some of the above Factory calls fails with duplicate keys you can just run those lines again and again until they don't fail. This way you can also generate even more data to test with if you want to.
 - Open https://localhost:8000/excel-download/ in web browser 
   - If this doesn't show the Excel download page then try logging first into https://localhost:8000/admin/ with user admin/admin and then retry opening the Excel download page
 - Click on the `Lataa raportointi-Excel kaikista tämän vuoden hakemuksista`, see that the Excel is downloaded ok and that it contains 52 rows
 - Click on the `Lataa Talpa-Excel kaikista tämän vuoden hakemuksista`, see that the Excel is downloaded ok and that it contains 52 rows
 - Click on `Lataa Talpa-Excel käsittelemättömistä hakemuksista`, see that the Excel is downloaded ok and that it contains 52 rows
 - After this clicking on `Lataa raportointi-Excel käsittelemättömistä hakemuksista` should give a notification "Ei uusia käsittelemättömiä hakemuksia." in the upper area of the window
 - Regenerate data to test Excel export with:
   - `docker exec -it kesaseteli-backend bash`
   - `python manage.py shell_plus`
   - `from applications.enums import EmployerApplicationStatus`
   - `from applications.models import EmployerApplication, EmployerSummerVoucher`
   - `EmployerSummerVoucher.objects.all().delete()`
   - `EmployerApplication.objects.all().delete()`
   - `from applications.models import EmployerApplication, EmployerSummerVoucher`
   - `from common.tests.factories import EmployerApplicationFactory, EmployerSummerVoucherFactory`
   - `for _ in range(51): EmployerSummerVoucherFactory(application=EmployerApplicationFactory(status=EmployerApplicationStatus.DRAFT))`
   - `for _ in range(52): EmployerSummerVoucherFactory(application=EmployerApplicationFactory(status=EmployerApplicationStatus.SUBMITTED))`
   - `for _ in range(53): EmployerApplicationFactory(status=EmployerApplicationStatus.DRAFT)`
   - NOTE: If some of the above Factory calls fails with duplicate keys you can just run those lines again and again until they don't fail. This way you can also generate even more data to test with if you want to.
 - Click on `Lataa raportointi-Excel käsittelemättömistä hakemuksista`, see that the Excel is downloaded ok and that it contains 52 rows

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

Tested locally in Docker that the backend's tests passed (i.e. "pytest . -vv").
Tested locally the Excel export similarly as described in the testing instructions in this PR (Not 100% the same but similarly).

NOTE:
 - **Colors, formatting and default column widths are removed** by this PR from the Excel output—the reason for this is that it did not seem possible to retain them using the xslx-streaming package without major efforts and/or hacks (e.g. monkeypatching the library's functionality). It was confirmed with the Kesäseteli's product owners that this is ok.

2022-09-20 08:48 UTC, karisal-anders commented
Please could you @nikomakela or @tuomas777 code review this? Thank you! We can code review this live together also if you prefer.

2022-09-20 11:04 UTC, mhieta reviewed
Added few comments regarding type declarations and hardcoded configuration value. @karisal-anders please check those.

2022-09-20 11:56 UTC, karisal-anders commented on backend/kesaseteli/applications/exporters/excel_exporter.py
> +    summer_vouchers,
Taken into account in 0a3e73f39b3ba789c5b4b6e6ac16fb79fae411f3

2022-09-20 11:56 UTC, karisal-anders commented on backend/kesaseteli/applications/exporters/excel_exporter.py
> +    is_template: bool = False,
Taken into account in 0a3e73f39b3ba789c5b4b6e6ac16fb79fae411f3

2022-09-20 11:56 UTC, karisal-anders commented on backend/kesaseteli/applications/views.py
> +                batch_size=50,
Taken into account in 0a3e73f39b3ba789c5b4b6e6ac16fb79fae411f3

2022-09-20 14:38 UTC, karisal-anders commented
Ok, so now tested more locally, added testing instructions for testing locally (See the description's testing section). This is ready for code review and testing! Please anyone of you @mhieta, @nikomakela or @tuomas777 if you have time could you code review this? Thank you!

2022-09-21 07:47 UTC, mhieta requested changes
@karisal-anders Code looks good now, but order-number (`järjestys`) in the output Excel is still not in correct order.

![button](https://user-images.githubusercontent.com/2784933/191445962-ac413b35-fc4d-40f4-8dfd-4c7647cfe03c.png)

![excel-download-bugi](https://user-images.githubusercontent.com/2784933/191445943-a13a0a40-e3eb-4261-8320-8bb884123217.png)

2022-09-22 15:04 UTC, karisal-anders commented
Alright, now tested this locally more extensively and I'm quite satisfied that this should work correctly now. Please could you @mhieta do a rereview? Commit b398f526636394b290822f9d1e7bf22bcdc49107 is new which should fix the sorting order in the Excel output. We can also do a live code review tomorrow.

2022-09-23 06:48 UTC, mhieta approved these changes
Looks good now 👍

2022-09-23 06:53 UTC, merged