Hl 697 handled
City-of-Helsinki/yjdh pull request #1974
Opened 2023-04-13 07:09 UTC by sirtawast

## Description :sparkles:

2023-04-20 10:12 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1974.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-26 12:30 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1974.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-26 12:31 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-26 12:31 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-26 12:33 UTC, terovirtanen commented
## TestCafe result is __success__ for https://handler-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-26 12:36 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kesaseteli-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-26 12:44 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-26 17:04 UTC, mjturt requested changes

2023-04-27 06:32 UTC, sirtawast commented on backend/benefit/applications/api/v1/application_batch_views.py
> +            app_status not in [ApplicationStatus.ACCEPTED, ApplicationStatus.REJECTED]
Very good! This is [implemented actually on serializer level](https://github.com/City-of-Helsinki/yjdh/blob/develop/backend/benefit/applications/api/v1/serializers/batch.py#L113) and can be removed all together as I think it's the place where this sort of logic should go in the first place.

2023-04-27 06:32 UTC, sirtawast commented on backend/benefit/applications/api/v1/application_batch_views.py
> +            matching_status = status_map[app_status]
Very good! This is [implemented actually on serializer level](https://github.com/City-of-Helsinki/yjdh/blob/develop/backend/benefit/applications/api/v1/serializers/batch.py#L113) and can be removed all together as I think it's the place where this sort of logic should go in the first place.

2023-04-27 06:44 UTC, sirtawast commented on backend/benefit/applications/tests/test_application_batch_api.py
> +def test_matching_status_map():
Removed, good practice round 😂

2023-04-27 07:26 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1974.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-27 07:26 UTC, terovirtanen commented
**YOUTH branch is deployed to platta: https://youth-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 07:26 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 07:28 UTC, terovirtanen commented
## TestCafe result is __success__ for https://handler-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 07:34 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 07:38 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kesaseteli-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 07:40 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 07:48 UTC, mjturt approved these changes
:+1: 

Maybe remove the commented code in the test before merge.

2023-04-27 08:13 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1974.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-27 08:15 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 08:16 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 08:18 UTC, terovirtanen commented
## TestCafe result is __success__ for https://handler-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 08:24 UTC, terovirtanen commented
## TestCafe employer result is __failed__ for https://kesaseteli-pr1974.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2023-04-27 08:27 UTC, terovirtanen commented
**YOUTH branch is deployed to platta: https://youth-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 08:42 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 10:42 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1974.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-27 10:43 UTC, terovirtanen commented
**YOUTH branch is deployed to platta: https://youth-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 10:48 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 10:49 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1974.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-27 10:52 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kesaseteli-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 10:57 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1974.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-27 11:51 UTC, merged