Harmonize docker compose files
City-of-Helsinki/yjdh pull request #1981
Opened 2023-04-17 11:31 UTC by sirtawast

Decided to cherry-pick this one out of NextJS. Makes it easier to swap builds and change between projects.

## Description :sparkles:

- Add an app name prefix instead of postgres so that docker can handle each service without deleting the existing one when switching to  develop another service
- Youth is not needed as handler is more extended version from it and browser-tests fail without handler AND youth

2023-04-18 10:42 UTC, arpargo requested changes

2023-04-18 11:55 UTC, sirtawast commented on docker-compose.tet-admin.yml
> +      - te-postgres
Good catch! I will fix it tomorrow.

2023-04-19 09:15 UTC, karisal-anders approved these changes
Things that could be improved but if you are in a hurry you can just merge as is:
 - Remove everything mentioning use of `docker-compose` as it doesn't work anymore with the current docker-compose YAML files (You can try it and it blows up), `docker compose` seems to be required.
  - Having a double prefix is probably not needed for pgdata, e.g. `yjdh-kesaseteli_ks-pgdata` is probably spurious, it could just be `yjdh-kesaseteli_pgdata`

2023-04-20 07:05 UTC, sirtawast commented
@arpargo could you re-test please 🙏

2023-04-20 07:12 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1981.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-20 07:19 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1981.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-20 07:20 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 07:21 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 07:23 UTC, terovirtanen commented
## TestCafe result is __success__ for https://handler-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 07:27 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kesaseteli-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 07:29 UTC, terovirtanen commented
**YOUTH branch is deployed to platta: https://youth-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 07:44 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 07:54 UTC, arpargo approved these changes
LGTM

2023-04-20 08:04 UTC, terovirtanen commented
**API branch is deployed to platta: https://kesaseteli-pr1981.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-04-20 08:05 UTC, terovirtanen commented
**YOUTH branch is deployed to platta: https://youth-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 08:16 UTC, terovirtanen commented
**EMPLOYER branch is deployed to platta: https://kesaseteli-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 08:20 UTC, terovirtanen commented
## TestCafe result is __success__ for https://youth-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 08:21 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://handler-pr1981.dev.hel.ninja** :rocket::rocket::rocket:

2023-04-20 08:21 UTC, terovirtanen commented
## TestCafe result is __success__ for https://kesaseteli-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 08:23 UTC, terovirtanen commented
## TestCafe result is __success__ for https://handler-pr1981.dev.hel.ninja :laughing::tada::tada::tada:

2023-04-20 14:00 UTC, karisal-anders approved these changes

2023-04-21 10:42 UTC, merged