HL-930: Release Please docs and git hook & CI modifications
City-of-Helsinki/yjdh pull request #2242
Opened 2023-09-01 14:27 UTC by mjturt

## Description :sparkles:

- Add Release Please documentation in readme
- Modify Git hooks documentation in readme
- Run also lerna & husky & lint-staged git hooks with pre-commit. Pre-commit is now the preferred git hook system.
- Add git hook to validate commit messages
- Add GitHub action to validate commit messages
- Add GitHub action to check for missing Django migrations (in benefit)

2023-09-01 15:16 UTC, mjturt commented on README.md
> +### Example workflow
What do you think, is this kind of w workflow something that could work for us?

2023-09-05 08:41 UTC, rikuke approved these changes

2023-09-06 09:49 UTC, terovirtanen requested changes

2023-09-06 09:49 UTC, terovirtanen commented on .github/workflows/conventional-commits.yml
> +    - '.github/workflows/conventional-commits.yml'
tarkoitus on varmaan ajaa tämä workflow aina kun pr:aan lisätään commit? Tämä taitaa nyt ajaa vain jos tulee muutos tähän filuun?

2023-09-06 09:49 UTC, terovirtanen commented on .github/workflows/conventional-commits.yml
> +        uses: webiny/action-conventional-commits@v1.1.0
Tarkistaako tämä vain viimeisen commitin ?

2023-09-06 20:35 UTC, mjturt commented on .github/workflows/conventional-commits.yml
> +        uses: webiny/action-conventional-commits@v1.1.0
Kaikki PR:n commitit

2023-09-06 20:39 UTC, mjturt commented on .github/workflows/conventional-commits.yml
> +    - '.github/workflows/conventional-commits.yml'
Meidän muissa workfloweissa on tuota viljelty, mutta nyt kun manuskaa tarkemmin katsoo niin eipä siinä kovin järkeä näytä olevan.

2023-09-07 05:18 UTC, terovirtanen approved these changes

2023-09-07 10:48 UTC, merged