Hl 963 ps
City-of-Helsinki/yjdh pull request #2281
Opened 2023-09-18 15:11 UTC by rikuke

## Description :sparkles:
Submitting an application manually as a handler does not create rows into the` bf_calculation_paysubsidy `table in the database, because the JSON payload it submits has an empty `pay_subsidies` list evaluates to not` None `which causes a branch in the calculation logic to skip the database insert.  This PR  fixes the issue by checking if the application is submitted by a handler and then makes sure that `pay_subsidy_data `is `None `and `pay_subsidies` is is not present in the `validated_data` dict.
## Issues :bug:

## Testing :alembic:
Pytest: pytest applications/tests/test_handler_application.py
Manually: create a new application as  a handler and then as a handler process the application.
## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2023-09-18 15:25 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2281.dev.hel.ninja** :rocket::rocket::rocket:

2023-09-18 15:29 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2281.dev.hel.ninja :laughing::tada::tada::tada:

2023-09-19 06:03 UTC, sirtawast requested changes

2023-09-19 06:03 UTC, sirtawast commented on backend/benefit/applications/api/v1/serializers/application.py
> +            print(required_attachment_types)
Remove print. Otherwise LGTM.

2023-09-19 10:00 UTC, rikuke commented on backend/benefit/applications/api/v1/serializers/application.py
> +            print(required_attachment_types)
whoops

2023-09-19 10:12 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2281.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-09-19 10:12 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2281.dev.hel.ninja** :rocket::rocket::rocket:

2023-09-19 10:12 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2281.dev.hel.ninja** :rocket::rocket::rocket:

2023-09-19 10:16 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2281.dev.hel.ninja :laughing::tada::tada::tada:

2023-09-19 14:27 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2281.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-09-19 14:27 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2281.dev.hel.ninja** :rocket::rocket::rocket:

2023-09-19 14:28 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2281.dev.hel.ninja** :rocket::rocket::rocket:

2023-09-19 14:31 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2281.dev.hel.ninja :laughing::tada::tada::tada:

2023-09-19 14:36 UTC, merged