feat: add callback for Talpa robot
City-of-Helsinki/yjdh pull request #2654
Opened 2023-12-21 15:04 UTC by rikuke

## Description :sparkles:

## Issues :bug:

## Testing :alembic:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2023-12-21 15:17 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2023-12-21 15:34 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2023-12-21 15:41 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2023-12-21 15:56 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2023-12-21 15:59 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-05 13:49 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-05 14:02 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-05 14:08 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-05 14:23 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-05 14:26 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-07 14:20 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-07 14:32 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-07 14:40 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-07 14:51 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-07 14:56 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-08 07:34 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-08 07:49 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-08 07:57 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-08 08:14 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-09 09:58 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-09 10:16 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-09 10:23 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-09 10:38 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-09 10:41 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-09 13:30 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-09 13:43 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-09 13:49 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-09 14:04 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-09 14:07 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-15 07:50 UTC, sirtawast requested changes

2024-01-15 07:50 UTC, sirtawast commented on backend/benefit/applications/api/v1/talpa_integration_views.py
> +                    applications.update(status=ApplicationStatus.REJECTED_BY_TALPA)
Can't do this. We would lose information if the handler approved or denied the application.

2024-01-15 07:50 UTC, sirtawast commented on backend/benefit/applications/api/v1/talpa_integration_views.py
> +                    applications.update(status=ApplicationStatus.REJECTED_BY_TALPA)
Must use flag `is_payment_rejected`, or other descriptive field like `talpa_status` etc.

2024-01-15 14:25 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2654.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-01-15 14:46 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-15 14:58 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja** :rocket::rocket::rocket:

2024-01-15 15:02 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2654.dev.hel.ninja :laughing::tada::tada::tada:

2024-01-16 07:33 UTC, sirtawast approved these changes

2024-01-16 07:45 UTC, merged