feat: add alteration notice API (HL-1158)
City-of-Helsinki/yjdh pull request #2856
Opened 2024-02-27 13:36 UTC by EmiliaMakelaVincit

## Description :sparkles:
Implements the creation and modification interfaces for application alterations.

2024-02-27 13:52 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2856.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-02-27 14:09 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2856.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-02-27 14:26 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2856.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 14:33 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2856.dev.hel.ninja :laughing::tada::tada::tada:

2024-02-27 14:50 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2856.dev.hel.ninja** :rocket::rocket::rocket:

2024-02-27 14:54 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2856.dev.hel.ninja :laughing::tada::tada::tada:

2024-03-04 09:20 UTC, rikuke commented on backend/benefit/applications/api/v1/serializers/application_alteration.py
> +            print(company, application.company)
These print statements can probably be removed ?

2024-03-04 09:33 UTC, rikuke requested changes

2024-03-04 09:33 UTC, rikuke commented on backend/benefit/applications/api/v1/serializers/application_alteration.py
> +            print(company.id, application.company.id)
Print statement

2024-03-05 08:57 UTC, rikuke approved these changes

2024-03-05 08:59 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2856.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-03-05 09:15 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2856.dev.hel.ninja** :rocket::rocket::rocket:

2024-03-05 09:21 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2856.dev.hel.ninja :laughing::tada::tada::tada:

2024-03-05 09:44 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2856.dev.hel.ninja :laughing::tada::tada::tada:

2024-03-05 10:50 UTC, merged