fix: add missing tags when saving decision text
City-of-Helsinki/yjdh pull request #2987
Opened 2024-05-14 08:49 UTC by rikuke

## Description :sparkles:
Wrap the decision text parts in
`<section id="paatos"><h1>{_("Päätös")}</h1></section>`
and 
`<section id="paatosteksti"><h1>{_("Päätöksen perustelut")}</h1></section>`
as required by the schema, when saving the decision into the database.
## Issues :bug:

## Testing :alembic:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2024-05-14 09:12 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2987.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-05-14 09:12 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2987.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-14 09:12 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2987.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-14 09:20 UTC, terovirtanen commented
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr2987.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-05-14 10:11 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2987.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-16 06:38 UTC, sirtawast requested changes

2024-05-16 06:38 UTC, sirtawast commented on backend/benefit/applications/tests/test_ahjo_decision_proposal_drafts.py
> +<sectionid="paatoksenperustelut"><h1>{_("Päätöksen perustelut")}</h1>{justification_text}</section>'
Typo with `<sectionid="`

2024-05-21 07:02 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr2987.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-21 07:03 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr2987.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-21 07:03 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr2987.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-05-21 07:09 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr2987.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-21 07:12 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr2987.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-21 08:20 UTC, merged