feat: adjust title of ahjo application record
City-of-Helsinki/yjdh pull request #3030
Opened 2024-05-16 09:28 UTC by rikuke

## Description :sparkles:
Modify the Ahjo record title so, that if the record is for an application and it is a update request, the word "täydennys" is added to the record title.
## Issues :bug:

## Testing :alembic:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2024-05-20 06:55 UTC, sirtawast requested changes

2024-05-20 06:55 UTC, sirtawast commented on backend/benefit/applications/services/ahjo_payload.py
> +        " täydennys," if request_type == AhjoRequestType.UPDATE_APPLICATION else ""
Using hardcoded static value is a bit sketchy.

2024-05-20 06:56 UTC, sirtawast commented on backend/benefit/applications/services/ahjo_payload.py
> +        " täydennys," if request_type == AhjoRequestType.UPDATE_APPLICATION else ""
Put it in a var at least.

2024-05-20 11:00 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr3030.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-05-20 11:00 UTC, terovirtanen commented
**HANDLER branch is deployed to platta: https://helsinkilisa-ui-handler-pr3030.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-20 11:00 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3030.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-20 11:08 UTC, terovirtanen commented
## TestCafe handler result is __failed__ for https://helsinkilisa-ui-handler-pr3030.dev.hel.ninja :crying_cat_face::anger::boom::boom:

2024-05-21 07:19 UTC, terovirtanen commented
**APPLICANT branch is deployed to platta: https://helsinkilisa-ui-pr3030.dev.hel.ninja** :rocket::rocket::rocket:

2024-05-21 07:19 UTC, terovirtanen commented
**API branch is deployed to platta: https://helsinkilisa-pr3030.api.dev.hel.ninja/healthz** :rocket::rocket::rocket:

2024-05-21 07:24 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-pr3030.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-21 07:25 UTC, terovirtanen commented
## TestCafe result is __success__ for https://helsinkilisa-ui-handler-pr3030.dev.hel.ninja :laughing::tada::tada::tada:

2024-05-21 08:19 UTC, merged